# Node.js 이미지 기반으로 설정
FROM node:20.12.2

# 작업 디렉토리 설정
WORKDIR /usr/src/app

# package.json 및 package-lock.json 복사
COPY package*.json ./

# 의존성 설치
RUN npm install

# 애플리케이션 소스 복사
COPY . .

# Next.js 빌드
# RUN npm run build

# 애플리케이션 실행 포트
EXPOSE 3000

# 실행 명령어
CMD ["npm", "run", "dev"]
