services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydb
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # 관리자 계정 이메일
      PGADMIN_DEFAULT_PASSWORD: admin # 관리자 계정 비밀번호
    ports:
      - '5050:80'
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
